DELIMITER //
CREATE TRIGGER set_due_date BEFORE INSERT ON Mission
FOR EACH ROW
BEGIN
    SET NEW.due_date = DATE_ADD(NEW.create_date, INTERVAL 72 HOUR);
END //
DELIMITER ;

CREATE TABLE Mission (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    parents_sn BIGINT UNSIGNED NOT NULL,
    child_sn BIGINT UNSIGNED NOT NULL,
    content VARCHAR(255) NOT NULL,
    price MEDIUMINT UNSIGNED NOT NULL,
    create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    status TINYINT UNSIGNED NOT NULL,
    CONSTRAINT fk_user_mission FOREIGN KEY (child_sn) REFERENCES User(serial_num) ON DELETE CASCADE,
    CHECK (status IN (1, 2, 3, 4, 5))
);