CREATE TABLE user (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    phone_num VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    birthdate DATE NOT NULL,
    account_info VARCHAR(6) NOT NULL,
    role TINYINT UNSIGNED NOT NULL,
    profile_id TINYINT NOT NULL DEFAULT 1
);