CREATE TABLE user (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    phone_num VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    birthdate DATE NOT NULL,
    account_info VARCHAR(6) NOT NULL,
    role TINYINT UNSIGNED NOT NULL,
    profile_id TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE score (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    child_id INT UNSIGNED NOT NULL,
    score TINYINT UNSIGNED DEFAULT 50,
    CONSTRAINT fk_user_id FOREIGN KEY (child_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE family (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    parents_id INT UNSIGNED NOT NULL,
    child_id INT UNSIGNED NOT NULL,
    CONSTRAINT fk_user_parents_id FOREIGN KEY (parents_id) REFERENCES User(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_child_id FOREIGN KEY (child_id) REFERENCES User(id) ON DELETE CASCADE,
    CONSTRAINT unique_family UNIQUE (parents_id, child_id)
);